interface ContentGenerationRequest {
  businessDetails: string;
  contentType: 'text' | 'image' | 'video';
  suggestion: string;
  tone: string;
  style: string;
  persona: string;
}

interface GeneratedContent {
  text?: string;
  imageCaption?: string;
  imagePrompt?: string;
  imageUrl?: string;
  videoCaption?: string;
  videoUrl?: string;
}

export async function generateSocialMediaContent(
  request: ContentGenerationRequest
): Promise<GeneratedContent> {
  const { businessDetails, contentType, suggestion, tone, style, persona } = request;

  // Extract business name from details
  const businessName = businessDetails.split('\n')[0]?.replace('Business: ', '') || 'Your Business';
  
  // Mock content generation - in a real implementation, this would call an AI service
  switch (contentType) {
    case 'text':
      return {
        text: generateTextContent(suggestion, tone, style, persona, businessName)
      };
    
    case 'image':
      return {
        imageCaption: generateImageCaption(suggestion, tone, businessName),
        imagePrompt: generateImagePrompt(suggestion, style),
        imageUrl: undefined // Would be generated by AI image service
      };
    
    case 'video':
      return {
        videoCaption: generateVideoCaption(suggestion, tone, businessName),
        videoUrl: undefined // Would be generated by AI video service
      };
    
    default:
      return {
        text: generateTextContent(suggestion, tone, style, persona, businessName)
      };
  }
}

function generateTextContent(suggestion: string, tone: string, style: string, persona: string, businessName: string): string {
  const templates = {
    professional: {
      informative: `🔍 ${suggestion}

At ${businessName}, we've observed that this approach can significantly impact your results. Here are key insights:

• Focus on understanding your audience's needs
• Implement data-driven strategies
• Measure and optimize continuously

What's your experience with this? Share your thoughts below! 👇

#Business #Strategy #Growth`,
      
      engaging: `💡 Here's something interesting about ${suggestion.toLowerCase()}...

We've been exploring this at ${businessName} and the results are fascinating! 

The key is to think differently about how we approach this challenge. Instead of following the crowd, consider:

✨ What unique perspective can you bring?
✨ How can you add genuine value?
✨ What would your ideal customer want to know?

Drop a comment and let's discuss! 🚀`,
      
      storytelling: `📖 A quick story about ${suggestion.toLowerCase()}...

Last month at ${businessName}, we faced a challenge that many of you might relate to. Here's what happened and what we learned:

[The situation was complex, but the solution was surprisingly simple...]

The lesson? Sometimes the best insights come from stepping back and looking at things from a fresh perspective.

Have you experienced something similar? I'd love to hear your story! 💬`
    },
    
    casual: {
      informative: `Hey everyone! 👋

Let's talk about ${suggestion.toLowerCase()}. This is something we're passionate about at ${businessName}, and I wanted to share some quick insights:

→ Start with the basics
→ Build momentum gradually  
→ Stay consistent with your efforts

It's not rocket science, but it works! What questions do you have about this?

#Tips #Learning #Community`,
      
      engaging: `Okay, real talk... 🗣️

${suggestion} is one of those things that sounds complicated but really isn't. At ${businessName}, we've simplified it down to this:

1. Know what you're trying to achieve
2. Take action (even small steps count!)
3. Learn from what happens
4. Repeat

That's it! No fancy strategies needed. Who's ready to give this a try? 💪`,
      
      storytelling: `So here's what happened... 😅

We were working on ${suggestion.toLowerCase()} at ${businessName} when everything went sideways. But you know what? That "failure" taught us more than any success ever could.

The real breakthrough came when we stopped overthinking and just... did the work.

Sometimes the best lessons come from the messiest experiences. Anyone else been there? 🙋‍♀️`
    }
  };

  const toneKey = tone.toLowerCase() as keyof typeof templates;
  const styleKey = style.toLowerCase() as keyof typeof templates[typeof toneKey];
  
  if (templates[toneKey] && templates[toneKey][styleKey]) {
    return templates[toneKey][styleKey];
  }
  
  // Fallback content
  return `${suggestion}

At ${businessName}, we believe in sharing valuable insights with our community. This topic is particularly important because it affects so many aspects of business growth.

Key takeaways:
• Understanding is the first step
• Implementation requires consistency
• Results come from sustained effort

What are your thoughts on this? Let's start a conversation! 

#Business #Insights #Community`;
}

function generateImageCaption(suggestion: string, tone: string, businessName: string): string {
  return `✨ ${suggestion}

${businessName} is excited to share this visual insight with you! 

What do you think about this approach? Share your thoughts in the comments! 👇

#Visual #Insights #${businessName.replace(/\s+/g, '')}`;
}

function generateImagePrompt(suggestion: string, style: string): string {
  return `Create a ${style} visual representation of "${suggestion}". Include modern design elements, professional color scheme, and clear typography. The image should be engaging and suitable for social media sharing.`;
}

function generateVideoCaption(suggestion: string, tone: string, businessName: string): string {
  return `🎥 ${suggestion}

Watch this quick video from ${businessName} to learn more about this important topic!

Don't forget to:
• Like if this was helpful
• Share with someone who needs to see this
• Follow for more insights

#Video #Tips #${businessName.replace(/\s+/g, '')}`;
}