'use server';

/**
 * @fileOverview This file contains the Genkit flow for refining content generated by the AI chatbot.
 *
 * refineGeneratedContent - A function that refines the AI-generated content based on user feedback.
 * RefineGeneratedContentInput - The input type for the refineGeneratedContent function.
 * RefineGeneratedContentOutput - The return type for the refineGeneratedContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RefineGeneratedContentInputSchema = z.object({
  originalContent: z.string().describe('The original content generated by the AI chatbot.'),
  feedback: z.string().describe('The user feedback on the generated content.'),
  tone: z.string().optional().describe('The desired tone of the content.'),
  persona: z.string().optional().describe('The desired persona of the content.'),
});
export type RefineGeneratedContentInput = z.infer<typeof RefineGeneratedContentInputSchema>;

const RefineGeneratedContentOutputSchema = z.object({
  refinedContent: z.string().describe('The refined content based on user feedback.'),
});
export type RefineGeneratedContentOutput = z.infer<typeof RefineGeneratedContentOutputSchema>;

export async function refineGeneratedContent(
  input: RefineGeneratedContentInput
): Promise<RefineGeneratedContentOutput> {
  return refineGeneratedContentFlow(input);
}

const refineContentPrompt = ai.definePrompt({
  name: 'refineContentPrompt',
  model: 'googleai/gemini-1.5-flash',
  input: {schema: RefineGeneratedContentInputSchema},
  output: {schema: RefineGeneratedContentOutputSchema},
  prompt: `You are an AI content refiner. You will receive the original content generated by an AI chatbot and feedback from the user. Use the feedback to refine the content so that it aligns with the user's brand and messaging and doesn't sound 'too AI-generated'. Take into account requested tone and persona.

Original Content: {{{originalContent}}}

Feedback: {{{feedback}}}

Tone: {{{tone}}}

Persona: {{{persona}}}

Refined Content:`, // Provide clear instructions
});

const refineGeneratedContentFlow = ai.defineFlow(
  {
    name: 'refineGeneratedContentFlow',
    inputSchema: RefineGeneratedContentInputSchema,
    outputSchema: RefineGeneratedContentOutputSchema,
  },
  async input => {
    const {output} = await refineContentPrompt(input);
    return output!;
  }
);
